### ISSUE TITLE
Created a dashboard for my college club website . 

### ISSUE THREAD

**Issue by Abiral-2724** [sestopus/hacktoberfest24#14]
Created a dashboard for my college club website , which aware people about hactoberfest 2024

**Comment by sestopus** [comment]
@Abiral-2724 ok. Do the task. Make sure you add the files in correct folder.

**Comment by sestopus** [comment]
also read the readme properly.

**Comment by Abiral-2724** [comment]
> @Abiral-2724 ok. Do the task. Make sure you add the files in correct folder.

done

**Comment by sestopus** [comment]
@Abiral-2724  make sure you read the Guide for adding WebDev Projects section in readme.
