### ISSUE TITLE
created a basic To-Do WEBAPP using HTML,CSS,JS. 

### ISSUE THREAD

**Issue by nikhilsingh1010** [sestopus/hacktoberfest24#20]

**Comment by nikhilsingh1010** [comment]
Created a basic TO-DO WEBAPP in which user can add the tasks which is to be done and can do the work more effectively without delay!

**Comment by sestopus** [comment]
@nikhilsingh1010  

Add your files in the respective folder
Also add your project name and small description in the same format as other files in the array ProjectFiles. See from line no 115(may be changed look for projectFiles) in index.html file.

**Comment by sestopus** [comment]
@nikhilsingh1010 make sure you read the Guide for adding WebDev Projects section in readme.

**Comment by nikhilsingh1010** [comment]
ok sure i will keep in mind

**Comment by sestopus** [comment]
Great! Star the repository, if you think.....
