### ISSUE TITLE
Redisgn the about page. add a hamburger menu botton in navbar.

### ISSUE THREAD

**Issue by sestopus** [sestopus/hacktoberfest24#24]

**Comment by ishita2704** [comment]
i want to do this, please assign me this

**Comment by ishita2704** [comment]
i did it, like this
![About Us - Hacktoberfest24 - Google Chrome 20-10-2024 09_15_30](https://github.com/user-attachments/assets/d363e0d8-93b4-4d1e-bf5d-6ba415d52b78)

**Comment by ishita2704** [comment]
I have raised a PR of solution kindly check

**Comment by sestopus** [comment]
Great!

**Comment by sestopus** [comment]
Star the repository! If you think.....
